[package]
name = "json_from_file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-serialize = "0.3.25"
serde = "1.0.195"
serde_json = "1.0.111"
